export const API_URL = 'https://api.unsplash.com';
export const API_URL_PHOTOS = `${API_URL}/photos`;
export const API_URL_TOKEN = 'https://unsplash.com/oauth/token';
export const API_URL_SIGN = 'https://unsplash.com/oauth/authorize';
export const API_ACCESS_KEY = 'W1hvLPsoeeJ9Dukl5pfTxtiehrJXl-4axgHF77b1RSE';
export const REDIRECT_URI = 'http://127.0.0.1:5500/';
export const RESPONSE_TYPE = 'code';
export const SECRET_KEY = 'SDfPdkoRAAiJlHH32p2pg2X0otsBuNeDaSxUv0XdXF4';
export const SCOPE = 'public read_user read_photos write_likes';
